package com.johnsontechinc.learnrealm.model;

import io.realm.RealmObject;
import io.realm.annotations.Ignore;
import io.realm.annotations.PrimaryKey;

/**
 * Created by ImL1s on 2017/4/6.
 * <p>
 * DESC:
 */

public class UserRealm extends RealmObject
{
    @PrimaryKey private int id;

    private String name;
    private int    age;

    @Ignore private int sessionId;

    // Standard getters & setters generated by your IDE…
    public String getName() { return name; }

    public void setName(String name) { this.name = name; }

    public int getAge() { return age; }

    public void setAge(int age) { this.age = age; }

    public int getSessionId() { return sessionId; }

    public void setSessionId(int sessionId) { this.sessionId = sessionId; }

    public int getId()
    {
        return id;
    }

    public void setId(int id)
    {
        this.id = id;
    }
}
